/**
 * Supabase Auth Adapter
 *
 * Replaces the hand-rolled JWT/session stack (worker/middleware/auth,
 * worker/database/services/AuthService, the JWT half of
 * worker/utils/authUtils) with Supabase-issued session tokens. The old
 * stack is left in place until Task 9 removes it — this file only adds the
 * new verification path so callers can migrate incrementally.
 *
 * Token source priority mirrors the old `extractTokenWithMetadata`:
 * `Authorization: Bearer <token>` first (what the frontend auth work in a
 * later task sends on every request), then a best-effort read of the
 * `sb-<project-ref>-auth-token` cookie that `@supabase/ssr` sets in the
 * browser for cookie-based session flows.
 */

import { createClient } from '@supabase/supabase-js';
import { UnauthorizedError } from 'shared/types/errors';
import type { AuthUser } from '../../types/auth-types';
import { createLogger } from '../../logger';

const logger = createLogger('SupabaseAuth');

export type { AuthUser };

/**
 * Minimal surface of a Supabase client this adapter depends on, narrowed so
 * tests can inject a fake without touching the network or the real SDK.
 * The real `SupabaseClient` returned by `createClient` structurally
 * satisfies this (its `auth.getUser` is a strict superset).
 */
export type SupabaseClientFactory = (
    url: string,
    key: string,
) => {
    auth: {
        getUser(token: string): Promise<{
            data: {
                user: { id: string; email?: string; user_metadata?: Record<string, unknown> } | null;
            };
            error: unknown;
        }>;
    };
};

const defaultClientFactory: SupabaseClientFactory = (url, key) => createClient(url, key);

/**
 * Reads SUPABASE_URL/SUPABASE_ANON_KEY without widening the generated `Env`
 * type. `worker-configuration.d.ts` is generated by `wrangler types` from
 * `wrangler.jsonc` bindings/vars and must not be hand-edited — same
 * precedent as `getSupabaseDbUrl` in `worker/database/pgConnection.ts` for
 * `SUPABASE_DB_URL`.
 */
function getConfigValue(env: Env, key: 'SUPABASE_URL' | 'SUPABASE_ANON_KEY'): string {
    const value = (env as unknown as Record<string, unknown>)[key];
    if (typeof value !== 'string' || value.length === 0) {
        throw new Error(`${key} is not configured`);
    }
    return value;
}

function resolveDisplayName(metadata: Record<string, unknown> | undefined): string | undefined {
    if (!metadata) {
        return undefined;
    }
    const candidate = metadata.display_name ?? metadata.full_name ?? metadata.name;
    return typeof candidate === 'string' && candidate.length > 0 ? candidate : undefined;
}

/**
 * Validates a Supabase access token and maps the response to this repo's
 * `AuthUser`. Never throws on a bad/expired token, a Supabase error, or an
 * unreachable client factory — every failure path resolves to `null`.
 * Callers that need a hard failure should use `requireUser`, which wraps
 * this in an `UnauthorizedError`.
 */
export async function getUserFromToken(
    env: Env,
    accessToken: string,
    clientFactory: SupabaseClientFactory = defaultClientFactory,
): Promise<AuthUser | null> {
    if (!accessToken) {
        return null;
    }

    try {
        const supabase = clientFactory(getConfigValue(env, 'SUPABASE_URL'), getConfigValue(env, 'SUPABASE_ANON_KEY'));
        const { data, error } = await supabase.auth.getUser(accessToken);

        if (error || !data.user || !data.user.email) {
            logger.debug('Supabase getUser did not return a usable user', { hasError: Boolean(error) });
            return null;
        }

        return {
            id: data.user.id,
            email: data.user.email,
            displayName: resolveDisplayName(data.user.user_metadata),
        };
    } catch (error) {
        logger.warn('Supabase token validation threw', error);
        return null;
    }
}

const BEARER_PREFIX = 'bearer ';
const SUPABASE_COOKIE_PREFIX = 'sb-';
const SUPABASE_COOKIE_SUFFIX = '-auth-token';
const BASE64_COOKIE_PREFIX = 'base64-';

function extractBearerToken(request: Request): string | null {
    const header = request.headers.get('Authorization');
    if (!header || !header.toLowerCase().startsWith(BEARER_PREFIX)) {
        return null;
    }
    const token = header.slice(BEARER_PREFIX.length).trim();
    return token.length > 0 ? token : null;
}

function parseCookieHeader(cookieHeader: string): Record<string, string> {
    const cookies: Record<string, string> = {};
    for (const pair of cookieHeader.split(';')) {
        const separatorIndex = pair.indexOf('=');
        if (separatorIndex === -1) {
            continue;
        }
        const name = pair.slice(0, separatorIndex).trim();
        const value = pair.slice(separatorIndex + 1).trim();
        if (name) {
            cookies[name] = value;
        }
    }
    return cookies;
}

/**
 * Best-effort extraction of the access token from a Supabase `@supabase/ssr`
 * auth cookie value. The value is either a raw JSON string or a
 * `base64-`-prefixed JSON string, encoding either the legacy
 * `[access_token, refresh_token, ...]` tuple or the current
 * `{ access_token, ... }` session object. Chunked cookies
 * (`sb-<ref>-auth-token.0`, `.1`, ... for oversized sessions) are not
 * reassembled here — the `Authorization` header is the primary path (see
 * module doc); this is a fallback, not the source of truth.
 */
function extractSupabaseCookieValue(rawValue: string): string | null {
    try {
        const decoded = decodeURIComponent(rawValue);
        const jsonText = decoded.startsWith(BASE64_COOKIE_PREFIX)
            ? atob(decoded.slice(BASE64_COOKIE_PREFIX.length))
            : decoded;
        const parsed: unknown = JSON.parse(jsonText);

        if (Array.isArray(parsed) && typeof parsed[0] === 'string') {
            return parsed[0];
        }
        if (parsed && typeof parsed === 'object' && typeof (parsed as Record<string, unknown>).access_token === 'string') {
            return (parsed as Record<string, unknown>).access_token as string;
        }
        return null;
    } catch {
        return null;
    }
}

function extractCookieToken(request: Request): string | null {
    const cookieHeader = request.headers.get('Cookie');
    if (!cookieHeader) {
        return null;
    }

    const cookies = parseCookieHeader(cookieHeader);
    const authCookieName = Object.keys(cookies).find(
        (name) => name.startsWith(SUPABASE_COOKIE_PREFIX) && name.endsWith(SUPABASE_COOKIE_SUFFIX),
    );
    if (!authCookieName) {
        return null;
    }

    return extractSupabaseCookieValue(cookies[authCookieName]);
}

/**
 * Resolves the authenticated user for a request, or throws
 * `UnauthorizedError`. Token source priority: `Authorization: Bearer
 * <token>` header, then the Supabase `sb-<ref>-auth-token` cookie.
 */
export async function requireUser(
    env: Env,
    request: Request,
    clientFactory: SupabaseClientFactory = defaultClientFactory,
): Promise<AuthUser> {
    const token = extractBearerToken(request) ?? extractCookieToken(request);
    if (!token) {
        throw new UnauthorizedError('Missing authentication token');
    }

    const user = await getUserFromToken(env, token, clientFactory);
    if (!user) {
        throw new UnauthorizedError('Invalid or expired session');
    }

    return user;
}
